# Generated by Django 4.0.5 on 2023-06-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria', models.CharField(blank=True, max_length=50, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name='Tipo')),
                ('ambiente', models.CharField(blank=True, max_length=50, verbose_name='Ambiente')),
                ('garantia', models.CharField(blank=True, max_length=50, verbose_name='Garantia')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
